### ISSUE TITLE
kbdneo2 build Driver Error

### ISSUE THREAD

**Issue by Daveismus** [neo-layout/neo-layout#18]
I get the following error
![grafik](https://user-images.githubusercontent.com/55088389/76468154-2d7b4200-63e3-11ea-93e5-3eace6e0251b.png)
If i try to use the kbdneo2 „Quelldateien“ and build my own driver

I didn't change any of the data yet.

**Comment by HenningJW** [comment]
It looks like you have to build the nsi installer now and you are fine.  You could also install it manually, the nsi files should help: https://github.com/neo-layout/neo-layout/blob/master/windows/Neo2.0_installer.nsi#L117

**Comment by Daveismus** [comment]
I get the following Error if I try to compile the nsi file
![grafik](https://user-images.githubusercontent.com/55088389/76727347-b11e9100-674b-11ea-8bf0-085717b8ee04.png)

**Comment by stxx796** [comment]
There are some issues with the DDK itself. The example files like kbdus and kbdgr don't work either.
I left a comment on the other issue tracker:
https://git.neo-layout.org/neo/neo-layout/issues/524#issuecomment-3159

**Comment by qwertfisch** [comment]
The NSIS installer is just a script for automatic installation of already compiled drivers. To compile kbdneo there were indeed problems because of different preconditions and procedures in Windows Driver Kit (there is no DDK anymore). I manged to create a new working solution in Visual Studio 2019, see [this issue](https://git.neo-layout.org/neo/neo-layout/issues/535).
