### ISSUE TITLE
Many issues - where to put them?

### ISSUE THREAD

**Issue by mielouk** [neo-layout/neo-layout#7]
After getting over the first big hurdles, I see the great benefits of this layout. Although I encountered also lots of problems which need to get addressed.
During the six weeks that I played around the [website](https://www.neo-layout.org/) is still 'under maintenance' and this repo seems to be abandoned while the mailing list sign up doesn't seem to work.
So where should I put my issues? Does someone read this?

**Comment by ThomasFeher** [comment]
Most activity, that I know of, is currently in the IRC channel **#neo** on **freenode.net**.

**Comment by doncatnip** [comment]
While this project might look like it is abandoned, I'm pretty sure there are lots of us neo users out there. It's kinda hard to change to anything else once you are comfy with it. I'd assume most are just not visible; quietly using the most awesome keyboard layout of all time without thinking much about it. It's been around a while now.

**Comment by ultimanet** [comment]
Ok, let's bring this repo and neo back to life again :)
I can support the project with e.g. webhosting and the implementation of a CI pipeline. 

@Isopod Do you have maintainer rights for the github repo? If no, who has?

**Comment by theAkito** [comment]
@ultimanet I can help with CI, as well.

**Comment by qwertfisch** [comment]
Maintainer rights are with me and at least two other people.

You are right, Neo has stalled for some months. I was trying to convert the previous data (Wiki, repository, issues) from the Trac instance but was prevented by personal things and mostly lack of motivation. There is already a lot of work done, so that we at least can have all data back to quite a usable platform.

The platform currently considered is Gitea, which is an opensource clone of Github (and a fork of Gogs). Already solved is the integration of the Subversion repository (which is already a converted clone here on Github) and the historical issues. I am trying to transfer the Github issues over to Gitea.

The wiki is another thing which would need more discussion. E.g. I am not sure if a Wiki is the ultimate and most suitable solution. Also the IRC is a good place for discussions but not for permanently providing solutions – but Github / Gitea issues also not. Maybe a question/answer site like Stackoverflow?

To stay on topic: you can put your issues here for the moment. It’s no problem to convert them over once the Gitea instance is usable for public.

@ultimanet Webhosting is already available. A CI pipeline sounds nice but this is such a small project without any new features, so … kind of overkill. But if you have suggestions for lightweight opensource tools, maybe create another issue here (for the moment), or ask in IRC.

**Comment by doncatnip** [comment]
> Gitea

Why ? What's wrong with github ?

**Comment by ultimanet** [comment]
@qwertfisch Thanks for joining the discussion so quickly! 

@doncatnip Agreed. Github (or Gitlab for example) provides us with everything needed: git, issue tracker, wiki, automation of the test and build pipeline,...

**Comment by theAkito** [comment]
> to Gitea

Can only agree with that. I host my own Gitea server and am very satisifed with it. Can only recommend. Definitely the best open source self-hosted Git server solution out there, right now.



> Maybe a question/answer site like Stackoverflow?

Either [NodeBB](https://nodebb.org/) or [Discourse](https://www.discourse.org/).



> CI pipeline sounds nice

[Drone](https://drone.io/) is easily to integrate with Gitea. I am running my own Drone server in conjunction with my own Gitea server and they work nicely with each other.

**Comment by theAkito** [comment]
> 
> 
> > Gitea
> 
> Why ? What's wrong with github ?

It's not open and it is restricted. You e.g. need to pay even for LFS and similar stuff. If you host your own stuff, you don't have to worry about that and you are _free_ to work as you please.

**Comment by doncatnip** [comment]
I'm just thinking practical merits here. If (the neo community) want to take political stand about _freedom_ it would make sense. I would not, because adhering to it strictly does bring quite some overhead - especially when we talk self-hosting.

> you e.g. need to pay even for LFS and similar stuff.

Is that and "similar stuff" really needed, though ?

**Comment by theAkito** [comment]
> 
> 
> I'm just thinking practical merits here. If (the neo community) want to take political stance about _freedom_ it would make sense. I would not, because adhering to it strictly does bring quite some overhead - especially when we talk self-hosting.
> 
> > you e.g. need to pay even for LFS and similar stuff.
> 
> Is that and "similar stuff" really needed, though ?

The "free" part was just one of many advantages. What's your point against having a personal solution?

**Comment by doncatnip** [comment]
A personal solution relies on that person. While github is not exactly public it does seem a tad more reliable than something hosted privately somewhere. I'm open for collaborative/decentralized solutions but I'm not sure I'd prefer private hosting over github just for the sake of not using github.

**Comment by mielouk** [comment]
@qwertfisch was quite adamant on self-hosting, which I totally understand. Much more control and power (and no Microsoft...)

Oh, and the stalling has been years, not months... I started using neo/bone in early 2018 and there hasn't been any change since then or years before that.

**Comment by theAkito** [comment]
> just for the sake of not using github.

Well, as I pointed out, it's just 1 positive point of many.



> A personal solution relies on that person.

In fact, I have been sitting 2 minutes at what I have written to find the right word. After all, I did not. I wanted to use a word, that implies that it's not dependent on some foreign dark giant, you have no control over. Rather you plant your own seed in your own garden, instead of relying on this giant to keep your stuff safe.
I also tried to say, that it does not have to be 1 single person. If we would spread responsibility across several people, there would be certainly at least 1 person at all times that keeps things together.

**Comment by doncatnip** [comment]
I think the practicality of it should have priority. Github has a bigger reach. It is convenient since a lot of people that use neo and could contribute probably already have github accounts.

All in all, this is an idealistic decision. It's fine. I can live with it. I probably wont create another account somewhere, though.

**Comment by theAkito** [comment]
> I think the practicality of it should have priority. Github has a bigger reach. It is convenient since a lot of people that use neo and could contribute probably already have github accounts.

Visit my Github profile. All the projects that are made by me on the front page, are mirrors of projects from my Gitea instance. This way they are hosted both ways with both benefits. You can set up something like that easily with hooks. It seems like you try to make little things seem like unbearable challenges.

> All in all, this is an ideologic decision. It's fine. I can live with it. I probably wont create another account somewhere, though.

Due to the above quote and this I see that you are apparently ignoring what people are saying here. I pointed out several times now, that the freedom part is ONE OF MANY good points. Got it?
The more I read what you have to say the more I see that you are basing your view on a quite "ideological decision".
Honestly, it seems like you just try to hate on self hosting, etc. for no good reason.

**Comment by doncatnip** [comment]
Oh this got hostile quite quickly. This wasn't my intention. I am sorry. I won't post in here again.

**Comment by theAkito** [comment]
> 
> 
> Oh this got hostile quite quickly. This wasn't my intention. I am sorry. I won't post in here again. (the first paragraph would have been enough - i genuinely see what you are saying here)

I attack ideas, not people. I attack what you say, not what you are. I did not agree with your opinion and I expressed that (harshly?).
Keep posting here, don't stop talking. Only if everyone joins the debate, it is the most fruitful.

**Comment by ultimanet** [comment]
> I think the practicality of it should have priority. Github has a bigger reach. It is convenient since a lot of people that use neo and could contribute probably already have github accounts.
> 
> All in all, this is an ideological decision. It's fine. I can live with it. I probably wont create another account somewhere, though.

I couldn't agree more. 

> ...that the freedom part is ONE OF MANY good points.

Name them and especially those which are relevant for this project... From my point of view, this project is first and foremost resource-limited.

**Comment by ThomasFeher** [comment]
I would prefer a solution that actually exists, than a solution that remains an expression of intention.

@qwertfisch 
Would it be possible to open up the current state, i.e. the repository on Gitea, publicly?
Concerning the Github issues: It's 9 of them … I mean, why bother transferring them?
Concerning the Wiki: Can't we also just start with an empty one and transfer things (manually) as needed?

**Comment by theAkito** [comment]
@ThomasFeher You are right. Gitea is fresher than ever and is right there, ready to be used.
There is also a feature in Gitea to automatically import Issues from a migrated repository, so no worries about that.

This way we can keep control of the project, without relying on something we can't predict its action from.

**Comment by qwertfisch** [comment]
> > Maybe a question/answer site like Stackoverflow?
> 
> Either [NodeBB](https://nodebb.org/) or [Discourse](https://www.discourse.org/).

No, these are forums. Stackoverflow has been very popular ever since because of the quite different paradigma of question/answers (and comments to answers) and scoring of these, which defines the order of answers.
There are several Q&A software tools around. It might be worth a look. But that is a discussion for another issue.

@ThomasFeher
Yes, I might open up the temporary site … I was unsure about migration of the Wiki pages because there is simply _no_ Wiki software that allows simple conversion of the Trac wiki pages without losing information. Even the title of pages is restricted! (Github and Gitea do not support titles with a dash in them, it will just be converted to a space.)

So, I might just convert the pages up to a state that is usable, forget about history and put them online. 

@mielouk
Yes, there was no progress in the Neo repository, because of two reasons:

1. No need to. The layout is finished, and the drivers for the major OSs are mostly finished. There are some bugs, but these depend on user setups and/or are not fixable.
2. The existence of this Github repo was unknown to the (IRC) community until May 2019 or so.

**Comment by Jonas-commits** [comment]
Whatever we do, as I personally prefer GitHub for convenience i'm fine with either. Most important thing is that there is a platform to easily create issues and Pull-Requests and we don't get lost in discusssion what to do.

**Comment by mielouk** [comment]
Reasons we need a working homepage, git(lab) site and a wiki, from least to most important:

1. To be able to show interested individuals what neo/bone is
2. To make the project visible and searchable
3. Prove that the project is not dead
4. Make the project forkable
5. Make fixes/hacks available, searchable and extendable
6. Show devs of other related projects that it is worth fixing their bugs/bad implementations (there is no such thing as "unfixable")
7. Write a keymap for the console, together
8. Mature to the level of Dvorak and Colemak

Are these enough reasons to get going @qwertfisch ?

@everybody feel free to add your own reasons! Preferably with continuous numbering, next one would be 9.

**Comment by mielouk** [comment]
I shot somewhat early, with just checking the (not yet linked) HP. Progress has been made!

https://gitea.neo.uber.space/neo/neo-layout

**Comment by erik55** [comment]
Great, when will this finally be done? Also the website should be editable within the git repo.

Why not just do it, change to gitea or whatever. Abandon the old svn. 

Und überhaupt könnten wir auch deutsch sprechen, weil hier mindestens ALLE deutsch verstehen sollten, da sie eine für die deutsche Sprache optimierte Tastaturbelegung verwenden. Wir können auch spanisch oder französisch, türkisch oder arabisch reden. Aber deutsch wäre sicher ganz passend.

Also, jetzt haben alle etwas mehr Zeit (oder auch nicht), da könnte man doch mal den Schritt wagen und etwas ändern. Das hier ist eine [Do-ocracy](https://de.wikipedia.org/wiki/Do-ocracy), keine ewige Plenarsitzung. Die meisten Dinge können rückgängiggemacht werden. Es gibt Kopien. 

Viele wollen helfen, Energie haben auch einige, Wissen und Fähigkeiten ist auch vorhanden. Also __los__!!

**Comment by mielouk** [comment]
If nobody is offended when we continue in German, I'm fine with it.

@qwertfisch hat die alten Repos schon nach Gitea [umgezogen](https://gitea.neo.uber.space/neo/neo-layout). Ich hab nicht mehr Zeit, aber genug um hier Zeit rein zu stecken. 

Einige Themen liegen mir sehr am Herzen, für die ich auch gerne Zeit investieren würde. Ich würde gerne eine (Vektor-?)Grafik des BONE-Layouts erstellen, wie sie auf [Wikipedia](https://de.wikipedia.org/wiki/Neo_(Tastaturbelegung)) zu finden ist. Das hab ich allerdings noch nie gemacht. Wenn man mir die richtigen Werkzeuge anweisen würde, könnte ich damit loslegen.

Ein anderes Projekt das ich gerne realisieren wollen würde ist eine BONE (vielleicht auch NEO) Keymap für die vconsole.conf. Ich nehme an das sie aus /usr/share/kbd/keymaps/i386/ gelesen werden. Mir ist nicht klar welche Keymap ich idealerweise als Basis nehmen sollte.
Die Datei /usr/share/kbd/keymaps/i386/qwertz/de-latin1.map(.gz) verweist auf:

> keymaps 0-2,4-6,8-10,12
alt_is_meta
include "qwertz-layout"
	altgr keycode  16 = at
control altgr keycode  16 = nul
	altgr keycode  50 = mu
include "linux-with-alt-and-altgr"
	plain keycode  83 = KP_Comma
include "compose.latin1"
include "euro2.map"
strings as usual

Können wir das zusammen aufdröseln? Was verweist hier auf was?

Wer hat Lust hier mit an zu packen? 

Von mir aus können wir uns gerne zu diesem Termin absprechen.

**Comment by qwertfisch** [comment]
Die Problematik mit Gitea/Github (doppelte Repoverwaltung) möchte ich am Samstag zur Sprache bringen, und vielleicht gibt es dann auch eine entsprechende Lösung.

@mielouk, Dein Engagement freut mich. Ich kann Dir technisch gerade nicht helfen (dazu müsste ich mich auch einlesen). Magst Du für die Vorschläge/Aufgaben jeweils ein eigenes Issue anlegen? (Hier oder gerne im Gitea) So gehen sie nicht verloren, sind geordnet, und andere Personen können dazu beitragen.

**Comment by erik55** [comment]
Diese nicht synchronisierte Dopplung ist schrecklich und muss schnellstmöglich aufgehoben werden. 

Hier nochmal die Themen für Samstag (können ersetzt oder ergänzt werden, ist nur eine grobe Idee): 

- Wie bekommt man wieder eine lauffähige Webseite hin, bei der man nicht den Eindruck hat, dass die Entwickler in den 1980er Jahren gestorben sind.
- Wie bekommt man eine Informationssammlung hin, die von mehreren Leuten einfach bearbeitet werden kann. 
- Und einen Bugtracker, der wieder funktioniert.
- Und ein Software-Repo, dass zeitgemäß ist, also einfach von vielen Leuten bearbeitet werden kann.

**Comment by qwertfisch** [comment]
In den letzten zwei Monaten hat sich viel getan und wird sich weiterhin tun:

- Die Webseite verweist aktuell direkt auf Gitea und auf Wikiseiten.
- Gitea als Bugtracker ist unter der [richtigen Domain](https://git.neo-layout.org/neo/neo-layout) erreichbar
  - Anmeldung ist auch mit einem Github-Account möglich (ein gleichnamiger Gitea-Account wird dabei automatisch angelegt) → https://git.neo-layout.org/user/oauth2/github
  - Das Hauptrepository ist gespiegelt auf Github.
  - Issues wird man zukünftig nur noch in Gitea anlegen können.
- Die alten Wikiseiten wurden nach Markdown konvertiert und sind temporär im Gitea-Wiki erreichbar. Damit ist eine Integration in neue Systeme sowie eine leichte Bearbeitung möglich.
- Die Homepage wird neu gestaltet (Design) und hilfreicher strukturiert. Die im Wiki eher verstreute Dokumentation wird auf der Hauptdomain zugreifbar statt im Gitea versteckt zu sein. (WIP)

Ich werde in Kürze die Issues im Github stilllegen, daher diese Wasserstandsmeldung. Bei Fragen, Anregungen, Problemen usw. einfach ein Issue im offiziellen Issuetracker öffnen.
